### PR TITLE
Allow to set scope in constructor and Doxygen improvements

### PR DESCRIPTION
**Pull request by Shatur**
In this PR I added third parameter to configure the name of the root scope.
I also noticed that you using Doxygen. I send some modernizations which you may like as a bonus.

### CODE REVIEW

**Comment by Galfurian** [comment]
Thanks for the improvements on Doxygen.

**Comment by Shatur** [comment]
Wait, I forgot to update the comments.

**Comment by Shatur** [comment]
Done. Comments mention current scope as "CPP" in this test, so I bring the old name back.

**Comment by Galfurian** [comment]
Uh my bad, sorry. In the meantime, I looked at the generated Doxygen, it is pretty neat, I like it.

**Comment by Shatur** [comment]
> Uh my bad, sorry. In the meantime, I looked at the generated Doxygen, it is pretty neat, I like it.

Yes, Awesome Doxygen indeed awesome :)

**Comment by Shatur** [comment]
Note, that I currently put `-D DOXYGEN_WARN_AS_ERROR=NO` (its the default) because you have some warnings about missing documentation. If / when you fix it, just replace `NO` with `YES` :)

**Comment by Galfurian** [comment]
I will fix them promptly. Thanks, for the heads up ;)

**Pull request merged**
